// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontSizes = {
 "sub": "0.75rem",
 "paragraph": "1rem",
 "heading": "1.5rem",
 "title": "3rem"
} as const;

export default fontSizes;