// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const spacing = {
 "4": "0.0625rem",
 "8": "0.5rem",
 "16": "1rem",
 "32": "2rem",
 "48": "3rem",
 "64": "4rem",
 "96": "6rem"
} as const;

export default spacing;